# Extra Env {{{
export CLICOLOR=1
# }}}

# Zsh Features {{{
# enable autocomplete history with up arrow
# man zshzle. Search for "History Control".
# man zshcontrib. Search for "up-line-or-beginning-search".
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# enable command editor
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line
# }}}

# External Features{{{
# }}}

